### ISSUE TITLE
Add int values to Level enum

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#111]
Hi, level is an enum without int values assigned. Can you add int values to them?

This way they can be queried and stored as ints. Maybe have a variable option like levelnum or something so it gets output this way? Saves space / cpu if needed.

**Comment by pmwmedia** [comment]
I could imagine a new placeholder `{level-code}` for format patterns that outputs 0 (OFF) ... 5 (TRACE).

@hc-codersatlas Could you provide a pull request?

**Comment by sezinkarli** [comment]
Hello there, I'd like to work on this if it's ok. Can you help me by giving me a starting point for this?

**Comment by pmwmedia** [comment]
I good starting point is [SeverityLevelToken.java](https://github.com/pmwmedia/tinylog/blob/v2.2/tinylog-impl/src/main/java/org/tinylog/pattern/SeverityLevelToken.java). This class outputs the severity level name. You could copy the class and output a severity code number instead of the name in your new class. Afterwards you can register your new format token class in [FormatPatternParser.java](https://github.com/pmwmedia/tinylog/blob/4bb47222a688da9409a88d85c3cda5d038e66d50/tinylog-impl/src/main/java/org/tinylog/pattern/FormatPatternParser.java#L133).

**Comment by sezinkarli** [comment]
Great thanks!

**Comment by sezinkarli** [comment]
Sorry to say that I was not able to manually test my changes because I'm not able to build the whole project. I'm getting this:

> [ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.10.1:javadocJar (default) on project tinylog-api-kotlin: Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.10.1:javadocJar failed: Guice provision errors:
> [ERROR]
> [ERROR] 1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://kotlinlang.org/api/latest/jvm/stdlib/, packageListUrl=https://kotlinlang.org/api/latest/jvm/stdlib/package-list)

**Comment by pmwmedia** [comment]
@sezinkarli I get the same exception if I use a computer behind a proxy. You can skip this step by running Maven with `-Dmaven.javadoc.skip=true`.
