### ISSUE TITLE
Correlation ID

### ISSUE THREAD

**Issue by mancvso** [tinylog-org/tinylog#122]
In batch processes, how can I tell the framework to log all entries with a correlation ID?

**Comment by pmwmedia** [comment]
It works in tinylog similar to SLF4J: https://dzone.com/articles/correlation-id-for-logging-in-microservices

Just use the class `ThreadContext` instead of `MDC` (https://tinylog.org/v2/logging/#context-values). For output, use the placeholder `{context: correlationId}` (https://tinylog.org/v2/configuration/#format-pattern).
