### ISSUE TITLE
[Question] Why did you choose to use JDK 9?

### ISSUE THREAD

**Issue by MairwunNx** [tinylog-org/tinylog#136]
I am very interested in why you use `JDK 9`? It has not been supported for a long time, there is `JDK 8` which has been supported for a very long time and there is still `JDK 11` and `13`, why not use them? 🧐 Is there any reason for this?

**Comment by pmwmedia** [comment]
The reason is that Oracle decided to remove `sun.reflect.Reflection` with Java 11. However, they introduce `java.lang.StackWalker` with Java 9 as an alternative. tinylog needs one of both classes for getting elements from stack trace without any performance issues. This is one of the reasons, why tinylog is such fast: https://tinylog.org/v2/benchmark/

tinylog decides at runtime which one of both classes should be use (`sun.reflect.Reflection` on Java 6-8 and `java.lang.StackWalker` on Java 9 and later). For being able to support both classes, you need to build tinylog with a JDK that supports both classes. Unfortunately, these are only JDK 9 or 10. It is not very elegant but the performance boost more than worth.

**Comment by MairwunNx** [comment]
Thanks, I'll know :)
