### ISSUE TITLE
Compress Backup Files

### ISSUE THREAD

**Issue by pmwmedia** [tinylog-org/tinylog#139]
After starting a new file, the rolling file writer should be able compress backup files optionally.

**Comment by sezinkarli** [comment]
Hello, can I work on this?

**Comment by pmwmedia** [comment]
I'd be more than happy. May I assign the Issue to you?

**Comment by sezinkarli** [comment]
Yes sure. I guess RollingFileWriter is the place to implement it?

**Comment by pmwmedia** [comment]
Yes, you are right, it is `RollingFileWriter`.

**Comment by sezinkarli** [comment]
I checked RollingFileWriter and have few questions. 
I'm using this config while debugging:

writer          = rolling file
writer.level    = debug
writer.format   = {level}: {message}
writer.file     = log_{count}.txt
writer.charset  = UTF-8
writer.buffered = true
writer.policies = startup, size: 1 kb
writer.backups  = 10


My questions are:
-Where should we add the "zip backups" property? Policies are related to log file renewal so it didnt seem right.
-Will we still remove backups based on the above value?
-path.getAllFiles() is always empty in my case and because of this I cant make writer.backups work. They keep on piling up. Do you have an idea why?

**Comment by pmwmedia** [comment]
To answer your questions:
1. I suggest to add a new (optional) property `writer.compress = gzip` (maybe we can add other compression formats in future)
2. Yes, I propose to delete uncompressed log files after the compression immediately. and to delete compressed backups 
as soon as there are more than configured.
3. Do you mean that `path.getAllFiles()` does not contain compressed backups due to another file extension like `.txt.gz`? I think the suffix has to be changed in [DynamicPath.java](https://github.com/pmwmedia/tinylog/blob/v2.2/tinylog-impl/src/main/java/org/tinylog/path/DynamicPath.java#L94) to enabled searching also for the new compression extension like `.txt.gz`.

**Comment by sezinkarli** [comment]
Thanks for the answers. In (3) I meant that even though I didnt do any changes in the code and set backups to 10, nothing is picked up in getAllFiles() (despite there are 30 log files there) so nothing is deleted. My log files keep piling up. 

When I use writer.file = log_{count}.txt it does not find any files. I changed it to an absolute path and it works.
Like this
writer.file     = c:/log/log_{count}.txt

**Comment by pmwmedia** [comment]
@sezinkarli This seems to be a bug! I will analyze it.

**Comment by sezinkarli** [comment]
Hey @pmwmedia, I'd like to unassign this if it's ok. I'm not able to find free time to work on this.

**Comment by pmwmedia** [comment]
Hi @sezinkarli, no problem.
