### ISSUE TITLE
Reload logging setup at runtime

### ISSUE THREAD

**Issue by ZZerog** [tinylog-org/tinylog#192]
Is possible reload setup at runtime as reload conf. file or programmatically (change logging level) ? 

Thx

**Comment by pmwmedia** [comment]
Changing the configuration at runtime isn't supported by tinylog 2 itself. However, if you only want to change the severity level, you can do it by implementing a wrapper for tinylog's logging backend. Here is an example from another user: https://github.com/pmwmedia/tinylog/issues/102#issuecomment-494391235

Since tinylog 2.3, it is also possible to extend directly from `TinylogLoggingProvider` which would require even less code than an the linked example implementation.
