### ISSUE TITLE
Support for custom time sources

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#218]
Hey there,

I'm looking forward to use tinylog for an Android project. In this project, I want to use the time obtained by a GPS receiver  (using a custom time library) instead of the Android system time for the timestamps of the log messages stored by tinylog.

I have had a look at the documentation as well as at the source code of tinylog but I don't have an idea on how to accomplish this. Can you give me a hint?

Thanks and best regards,

Jens

**Comment by pmwmedia** [comment]
Hi Jens,

Unfortunately, tinylog 2 does not support registration of custom format pattern tokens. tinylog 3 will support such custom tokens. However, this won't help you right now.

Which writer do you use? You could copy the source of the writer you need ([tinylog-impl/src/main/java/org/tinylog/writers](https://github.com/tinylog-org/tinylog/tree/v2.4/tinylog-impl/src/main/java/org/tinylog/writers)), implement your [own custom time library token](https://github.com/tinylog-org/tinylog/blob/v2.4/tinylog-impl/src/main/java/org/tinylog/pattern/Token.java), and create all tokens you want to output manually in your writer instead of parsing the format pattern.

I know it is not the most elegant solution, but the only one that comes to my mind. You can find the official documentation of implementing a custom writer on the tinylog website: https://tinylog.org/v2/extending/#custom-writer

If you need any support, just let me know :)

**Comment by ghost** [comment]
Hey Martin,

sorry for my belated reply. It's pretty busy here at work at the moment....
Currently, I'm using the RollingFileWriter. I plan to have a look at your proposal later this week but I think that I already get the idea.

Bests,

Jens

**Comment by pmwmedia** [comment]
That's great to read :) I will close this issue.
