### ISSUE TITLE
SLF4J binding

### ISSUE THREAD

**Issue by pmwmedia** [tinylog-org/tinylog#45]
Reimplementation of [SLF4J binding](https://github.com/pmwmedia/tinylog/tree/v1.2/slf4j-binding) for tinylog 2.0:

- [x] Create project slf4j-tinylog
- [x] Implement [ILoggerFactory](https://www.slf4j.org/api/org/slf4j/ILoggerFactory.html)
- [x] Logger should implement [LocationAwareLogger](https://www.slf4j.org/api/org/slf4j/spi/LocationAwareLogger.html)
- [x] Add and implement classes [StaticLoggerBinder](https://www.slf4j.org/api/org/slf4j/impl/StaticLoggerBinder.html), [StaticMDCBinder](https://www.slf4j.org/api/org/slf4j/impl/StaticMDCBinder.html) and [StaticMarkerBinder](https://www.slf4j.org/api/org/slf4j/impl/StaticMarkerBinder.html)
- [x] Write JUnit tests
- [x] Add readme text file

**Comment by yegeniy** [comment]
Consider naming this dependency `slf4j-tinylog`, since people who will be relying on this dependency are likely to be familiar with SLF4J, which has more-or-less set up the convention of `slf4j-<logger>`:

Search for `binding` under https://mvnrepository.com/artifact/org.slf4j for some examples, such as `slf4j-log4j12`, `slf4j-simple`, `sl4j-nop`. 
 
Log4j2 `log4j-slf4j-impl-2` and Logback `logback-classic` (?) have somewhat inconsistent titles for their SLF4J bindings. I have a hunch that the inconsistency may be a subtle contributor to the common dependency issues that tend to occur with setting up SLF4J bindings for log4j2 and logback.

**Comment by pmwmedia** [comment]
I'm convinced and have updated the tasks.

**Comment by yegeniy** [comment]
🆒  Glad to see our many months of lobbying, backchanneling, and bribes have paid off
