### ISSUE TITLE
[Question] How to show parent call in logging format?

### ISSUE THREAD

**Issue by frnusmartobjects** [tinylog-org/tinylog#62]
We have a wrapper around TinyLog library, and when using our methods that delegate to TinyLog, the information that appears in the log for the placeholders {class}, {class_name} and {method} is the one of our wrapper.

Is it possible to select the "call stack level" to use for logging?

**Comment by pmwmedia** [comment]
Just use [LogEntryForwarder](https://github.com/pmwmedia/tinylog/blob/v1.3/tinylog/src/org/pmw/tinylog/LogEntryForwarder.java) instead of [Logger](https://github.com/pmwmedia/tinylog/blob/v1.3/tinylog/src/org/pmw/tinylog/Logger.java). The class LogEntryForwarder is designed to receive log entries from wrappers and other logging APIs.

**Comment by frnusmartobjects** [comment]
Thank you for your help

**Comment by pmwmedia** [comment]
You are welcome :-)
