### ISSUE TITLE
Support for running without a config file

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#86]
Hi, using Tinylog as part of another framework (great work) and wish to integrate the configuration. Currently using `System.setProperty` on startup after reading in the main config file. Is there a better way to do this? I couldn't find it in the docs. Can the Config be called directly? i.e. looking for a programmatic way.

As an improvement, can the loading code support this so that if a System property, e.g. noconfigfile = true is provided then it'll skip and not try to read a config file (which improves loading time)?

Thanks!

**Comment by pmwmedia** [comment]
If you use tinylog 1.x, you can use the fluent API for configuring tinylog programmatically: https://tinylog.org/configuration#fluent. For tinylog 2.x, I dropped this feature, because everyone uses configuration files in real world applications.

Reading the configuration from a file is pretty fast. Especially if `tinylog.properties` is part of your JAR, loading the configuration should be as fast as loading any class.
