### ISSUE TITLE
Non-blocking writerThread implementation

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#88]
Hi, most of log4j2's async performance comes from https://lmax-exchange.github.io/disruptor/. Has this been considered for the writerThread implementation? It currently uses mutex / synchronization. Maybe a similar route would just be using a non blocking queue e.g. [disruptor](https://github.com/conversant/disruptor) or similar from [JCTools](https://github.com/JCTools/JCTools).

Thanks!

**Comment by pmwmedia** [comment]
When I started developing tinylog 2, I created three different writing thread implementations. One of them was based on LMAX Disruptor. Based on benchmarks, I chose the current writing thread implementation, because it could output slightly more log entries per second than the LMAX Disruptor based implementation.

If anyone can implement a writing thread implementation that can output more log entries per second than the current implementation (proven by benchmarks), I would be pleased to integrate it into tinylog.

**Comment by re-thc** [comment]
Thanks. Curious to know what was the currency settings at the time (i.e. use case). Was like a webserver with many threads that would log, e.g. in a HTTP server? Definitely the mutex/current approach would be better when there's less contention. What settings did you pick for blocking strategy? LMAX does generate quite a bit of garbage. More simply using just a non-blocking queue might be better.

**Comment by pmwmedia** [comment]
I have benchmarked the number of log entries that can be processed per second. Performance is always a critical question. Often, bottlenecks are not where expected and some optimizations can make it worse, even if they look promising. Therefor, the best way is writing a benchmark for a component to verify, if it is really slow, and benchmarking possible replacements.

For tinylog 2, I have developed three different writing thread implementations and run the benchmark https://tinylog.org/v2/benchmark/ for all of them.
